name: my_vocab
description: A new Flutter application.

version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^0.17.4
  cupertino_icons: ^1.0.2
  easy_localization: ^3.0.0
  equatable: ^2.0.0
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  flutter_dotenv: ^4.0.0-nullsafety.0
  flutter_login_facebook: ^1.0.0-nullsafety.1
  flutter_spinkit: ^4.1.2+1
  flutter_svg: ^0.19.3
  fluttertoast: ^7.1.8
  font_awesome_flutter: ^8.11.0
  google_sign_in: ^5.0.0
  hive: ^1.4.4+1
  http: ^0.13.0
  intl: ^0.17.0
  modal_progress_hud: ^0.1.3
  path_provider: ^2.0.1
  provider: ^4.3.3

dependency_overrides:
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.4
  effective_dart: ^1.2.4
  hive_generator: ^0.8.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - Assets/Vectors/bookReading.svg
    - Assets/Vectors/welcomeBack.svg
    - Assets/Vectors/SignUp.svg
    - Assets/Vectors/googleLogo.svg
    - Assets/Vectors/error.svg
    - Assets/Vectors/empty.svg
    - Assets/images/profile.png
    - Assets/langs/en-US.json
    - Assets/langs/hi-IN.json

  fonts:
    - family: Montserrat

      fonts:
        - asset: Assets/Fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: Assets/Fonts/Montserrat-Light.ttf
          weight: 400
        - asset: Assets/Fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: Assets/Fonts/Montserrat-Bold.ttf
          weight: 600
        - asset: Assets/Fonts/Montserrat-Black.ttf
          weight: 700
        - asset: Assets/Fonts/Montserrat-ExtraBold.ttf
          weight: 800
flutter_intl:
  enabled: true
